## https://docs.netlify.com/routing/redirects/rewrites-proxies/
[[redirects]]
  from = "/resources/*"
  to = "https://mistaya.github.io/aadventure_resources/:splat"
  status = 200

[[redirects]]
  from = "/resources2/*"
  to = "https://mistaya.github.io/aadventure_resources2/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
